### PR TITLE
Fix/start stop message format

### LINKED ISSUE #431: start/stop subsystem message formatting doesnt include %s for name.
```bash
apx noble stop
```
```
 INFO  Stopping container…%!(EXTRA string=noble)
apx-noble
 INFO  Stopped container.%!(EXTRA string=noble)
```
```bash
apx noble start
```
```
 INFO  Starting container…%!(EXTRA string=noble)
apx-noble
 INFO  Started container.%!(EXTRA string=noble)
```

### PR DESCRIPTION
**Pull request by jardon**
this includes two changes:
1. add `%s` to starting/stopping messages
2. silence stdout for non-captureoutput dbox commands.

the second change cleans up the output of the command output which in the case of starting/stopping, silences the distrobox printing the container name for no good reason.  this can be dropped or split out if requested.

```bash
./apx noble stop
```
```
 INFO  Stopping subsystem noble…
 INFO  Stopped subsystem.
```
```bash
./apx noble start
```
```
 INFO  Starting subsystem noble…
 INFO  Started subsystem.
```
closes #431

### CODE REVIEW

**Comment by jardon** [comment]
i could also just remove the vars from the cmdr.info statements all together instead.  either way works for me.

**Comment by jardon** [comment]
i dont think i like the mismatch of "container" and "subsystem name"

**Review by kbdharun — APPROVED** [review]
LGTM, yeah we could probably rename the container strings with subsystem instead. Let me know if you are performing the change, will lock the component on Weblate.

File: cmd/runtime.go [hunk 1]
```diff
@@ -333,7 +333,7 @@ func runPkgCmd(subSystem *core.SubSystem, command string, cmd *cobra.Command, ar
 			return fmt.Errorf(apx.Trans("runtimeCommand.error.stoppingContainer"), err)
 		}
 
-		cmdr.Info.Printfln(apx.Trans("runtimeCommand.info.stoppedContainer"), subSystem.Name)
+		cmdr.Info.Printfln(apx.Trans("runtimeCommand.info.stoppedContainer"))
```
Comment (taukakao) [inline cmd/runtime.go:336]: I'm confused. Why are you removing the name if you added %s to the string?

Comment (jardon) [reply cmd/runtime.go:336]: sorry that wasnt very clear.  i removed it from the started/stopped message, but not the starting/stopping message

Comment (taukakao) [reply cmd/runtime.go:336]: Ah, I see.

**Comment by jardon** [comment]
@kbdharun i updated the strings to say subsystem instead. you good with it?
