### PR TITLE
fix:[#476] return error code on stack delete failure

### LINKED ISSUE #476: False success on stack deletion failure
When attempting to delete a stack that is currently used by subsystems, Apx GUI incorrectly displays "stack deleted", even though the underlying `apx stacks rm` command fails.

### PR DESCRIPTION
**Pull request by lancebord**
Properly returns an error when attempting to delete a stack that is currently used by subsystems.

Note: there are similar places in this source file where there are logged errors but a `return nil`. Not sure if those should also be looked at but may lead to similar issues in the future.

Closes: #476

### CODE REVIEW

**Review by mirkobrombin — APPROVED** [review]

File: internal/cli/stacks.go [hunk 1]
```diff
@@ -284,7 +284,7 @@ func (c *StacksRmCmd) Run() error {
 			})
 		}
 		Apx.CLI.Table(headers, data)
-		return nil
+    		return fmt.Errorf(Apx.LC.Get("stacks.rm.error.inUse"), len(subSystems))
```
Comment (NN708) [inline internal/cli/stacks.go]:
```suggestion
		return fmt.Errorf(Apx.LC.Get("stacks.rm.error.inUse"), len(subSystems))
```

**Review by NN708 — CHANGES_REQUESTED** [review]

**Review by NN708 — APPROVED** [review]
